//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.FinalnyjjProekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отделы.
    /// </summary>
    // *** Start programmer edit section *** (Отделы CustomAttributes)

    // *** End programmer edit section *** (Отделы CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтделыE", new string[] {
            "Код as \'Код\'",
            "Наимнование as \'Наимнование\'",
            "Организации as \'Организации\'",
            "Организации.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Организации.Наименование"})]
    [MasterViewDefineAttribute("ОтделыE", "Организации", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ОтделыL", new string[] {
            "Код as \'Код\'",
            "Наимнование as \'Наимнование\'",
            "Организации.Наименование as \'Наименование\'"})]
    public class Отделы : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fНаимнование;
        
        private IIS.FinalnyjjProekt.Организации fОрганизации;
        
        // *** Start programmer edit section *** (Отделы CustomMembers)

        // *** End programmer edit section *** (Отделы CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Отделы.Код CustomAttributes)

        // *** End programmer edit section *** (Отделы.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Отделы.Код Get start)

                // *** End programmer edit section *** (Отделы.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Отделы.Код Get end)

                // *** End programmer edit section *** (Отделы.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отделы.Код Set start)

                // *** End programmer edit section *** (Отделы.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Отделы.Код Set end)

                // *** End programmer edit section *** (Отделы.Код Set end)
            }
        }
        
        /// <summary>
        /// Наимнование.
        /// </summary>
        // *** Start programmer edit section *** (Отделы.Наимнование CustomAttributes)

        // *** End programmer edit section *** (Отделы.Наимнование CustomAttributes)
        [StrLen(255)]
        public virtual string Наимнование
        {
            get
            {
                // *** Start programmer edit section *** (Отделы.Наимнование Get start)

                // *** End programmer edit section *** (Отделы.Наимнование Get start)
                string result = this.fНаимнование;
                // *** Start programmer edit section *** (Отделы.Наимнование Get end)

                // *** End programmer edit section *** (Отделы.Наимнование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отделы.Наимнование Set start)

                // *** End programmer edit section *** (Отделы.Наимнование Set start)
                this.fНаимнование = value;
                // *** Start programmer edit section *** (Отделы.Наимнование Set end)

                // *** End programmer edit section *** (Отделы.Наимнование Set end)
            }
        }
        
        /// <summary>
        /// Отделы.
        /// </summary>
        // *** Start programmer edit section *** (Отделы.Организации CustomAttributes)

        // *** End programmer edit section *** (Отделы.Организации CustomAttributes)
        [PropertyStorage(new string[] {
                "Организации"})]
        [NotNull()]
        public virtual IIS.FinalnyjjProekt.Организации Организации
        {
            get
            {
                // *** Start programmer edit section *** (Отделы.Организации Get start)

                // *** End programmer edit section *** (Отделы.Организации Get start)
                IIS.FinalnyjjProekt.Организации result = this.fОрганизации;
                // *** Start programmer edit section *** (Отделы.Организации Get end)

                // *** End programmer edit section *** (Отделы.Организации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отделы.Организации Set start)

                // *** End programmer edit section *** (Отделы.Организации Set start)
                this.fОрганизации = value;
                // *** Start programmer edit section *** (Отделы.Организации Set end)

                // *** End programmer edit section *** (Отделы.Организации Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтделыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтделыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтделыE", typeof(IIS.FinalnyjjProekt.Отделы));
                }
            }
            
            /// <summary>
            /// "ОтделыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтделыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтделыL", typeof(IIS.FinalnyjjProekt.Отделы));
                }
            }
        }
    }
}
